package org.derek.processor.writer;

import org.derek.annotation.ViewInjector;
import org.derek.processor.util.IOUtil;

import java.io.IOException;
import java.io.Writer;

import javax.annotation.processing.ProcessingEnvironment;
import javax.lang.model.element.VariableElement;

public class DefaultJavaFileWriter extends AbsWriter {

    public DefaultJavaFileWriter(ProcessingEnvironment mProcessingEnv) {
        super(mProcessingEnv);
    }

    /**
     * 内部类有问题
     * @param writer
     * @param info
     * @throws IOException
     */
    @Override
    protected void generateImport(Writer writer, InjectorInfo info) throws IOException {
        IOUtil.print("===================generateImport========================");
        writer.write("package " + info.packageName + " ;");
        writer.write("\n\n");
        writer.write("import org.derek.butter.adapter.InjectAdapter ;");
        writer.write("\n");
        writer.write("import org.derek.butter.ViewFinder;");

        writer.write("\n\n\n");
        writer.write("/* This class is generated by Simple ViewInjector, please don't modify! */ ");
        writer.write("\n");
        writer.write("public class " + info.newClassName
                + " implements InjectAdapter<" + info.classlName + "> { ");
        writer.write("\n");
        writer.write("\n");
        // 查找方法
        writer.write("  public void injects(" + info.classlName
                + " target)  { ");
        writer.write("\n");
    }

    @Override
    protected void writeField(Writer writer, VariableElement element, InjectorInfo info) throws IOException {
        IOUtil.print("===================writeField========================");
        ViewInjector injector = element.getAnnotation(ViewInjector.class);
        if (injector == null)
            return;
        String fieldName = element.getSimpleName().toString();
        writer.write("      target." + fieldName + " =  ViewFinder.findViewById(target, " + injector.value() + "  ) ; ");
        writer.write("\n");
    }

    @Override
    protected void writeEnd(Writer writer) throws IOException {
        IOUtil.print("===================writeEnd========================");
        writer.write("  }");
        writer.write("\n\n");
        writer.write(" } ");
    }
}
